defaults: &defaults
  adapter: mysql
  encoding: utf8
  pool: 5

development:
  host: localhost
  database: game_demo_development
  user: root
  password:
  <<: *defaults

test:
  host: localhost
  database: game_demo_test
  user: root
  password:
  <<: *defaults

production:
  host: localhost
  database: game_demo_production
  user: root
  password:
  <<: *defaults
